name: Run Playwright Tests and Deploy Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p reports
          # Copy report files to reports directory
          cp -r playwright-report/* reports/
          # Add cache control headers to index.html
          sed -i '1i<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate, max-age=0">' reports/index.html
          sed -i '2i<meta http-equiv="Pragma" content="no-cache">' reports/index.html
          sed -i '3i<meta http-equiv="Expires" content="0">' reports/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./reports
          publish_branch: gh-pages